apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: ElasticSearch
spec:
  title: 'ElasticSearch'
  url: 'https://www.elastic.co/cn/'
  gitRepo: 'https://github.com/elastic/elasticsearch'
  author: 'Sealos'
  description: 'Elasticsearch is a distributed search and analytics engine, scalable data store and vector database optimized for speed and relevance on production-scale workloads. Elasticsearch is the foundation of Elastic’s open Stack platform. Search in near real-time over massive datasets, perform vector searches, integrate with generative AI applications, and much more.'
  readme: 'https://raw.githubusercontent.com/elastic/elasticsearch/refs/heads/main/README.asciidoc'
  icon: 'https://www.elastic.co/apple-touch-icon.png'
  templateType: inline
  locale: en
  categories:
    - tools
  defaults:
    app_host:
      type: string
      value: elasticsearch-${{ random(8) }}
    app_name:
      type: string
      value: elasticsearch-${{ random(8) }}
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ${{ defaults.app_name }}
spec:
  version: 9.3.3
  http:
    service:
      spec:
        type: ClusterIP
  nodeSets:
    - name: default
      # 调整副本数量
      count: 1
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                limits:
                  memory: 4Gi
                  cpu: 4
                requests:
                  memory: 2Gi
                  cpu: 2
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi